version: 2
jobs:
    build-job:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/project
        steps:
            - checkout
            - run:
                name: "Run Hugo"
                command: HUGO_ENV=production hugo -v -s ~/project/
            - run:
                name: "Generate Tag"
                command: |
                    increment=1
                    tag=$(git tag | sed '$!d')
                    if [[ -z $tag ]] ; then
                    	git tag -a v1.0 -m 'Version 1.0'
                    else
                    	aux=$(echo "$tag" | grep -o -E '[0-9]+')
                        real=$(echo "$aux" | head -n 1)
                        decimal=$(echo "$aux" | sed '$!d')
                    	if [[ $decimal == 9 ]] ; then
                            num=$(expr $real + $increment)
                    	    version="v$num.0"
                    	else 
                            num=$(expr $decimal + $increment)
                    	    version="v$real.$num"
                    	fi
                    	echo "Tag $version"
                        git tag -a $version -m 'Version $version'
                    fi
                    git push --tags
        
    deploy-job:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/project
        steps:
            - checkout
            - run:
                name: "Run Hugo"
                command: HUGO_ENV=production hugo -v -s ~/project/
            - add_ssh_keys
            - run:
                name: Push to git
                command: |
                    git config --global user.email "citrix.ko@gmail.com"
                    git config --global user.name "CircleCI"
                    git add docs/
                    git commit -m "Release"
                    git push origin master

workflows:
    version: 2
    build-deploy:
        jobs:
            - build-job
            - deploy-job:
                requires:
                    - build-job
                filters:
                    branches:
                        only: master
